version: '3'

volumes:

  mariadb: {driver: local, name: mariadb, driver_opts: {type: none, o: bind, device: /home/cyuuki/data/mariadb}}

  wordpress: {driver: local, name: wordpress, driver_opts: {type: none, o: bind, device: /home/cyuuki/data/wordpress}}

  portainer_data:

networks:

  cyuuki:
      name: cyuuki
      driver: bridge

services:

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    volumes: [wordpress:/var/www/html]
    env_file:
      - .env
    restart: always
    depends_on:
      - wordpress
    networks:
      - cyuuki
    ports: [443:443]

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes: [wordpress:/var/www/html]
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - cyuuki

  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes: [mariadb:/var/lib/mysql]
    env_file:
      - .env
    restart: always
    networks:
      - cyuuki
    
  # redis:
  #   build: requirements/bonus/redis
  #   image: redis
  #   container_name: redis
  #   env_file:
  #     - .env
  #   restart: always
  #   networks:
  #     - cyuuki
  #   ports: [6379:6379]

  # adminer:
  #   build: requirements/bonus/adminer
  #   image: adminer
  #   container_name: adminer
  #   volumes: [wordpress:/var/www/html]
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - cyuuki
  # ftp:
  #   build: requirements/bonus/ftp
  #   image: ftp
  #   container_name: ftp
  #   volumes: [wordpress:/ftp]
  #   env_file:
  #     - .env
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "21:21"
  #     - "20:20"
  #     - "21000-21000:21000-21000"
  #   networks:
  #     - cyuuki
  # site:
  #   build: requirements/bonus/site
  #   image: site
  #   container_name: site
  #   restart: always
  #   networks:
  #     - cyuuki
  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #     - "9000:9000"
  #     - "9443:9443"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - portainer_data:/data

